"""Shared auth helpers for integration RPC scripts."""

import os
import ssl
from typing import List, Optional


def read_local_admin_key() -> str:
    """Load persisted local admin key generated by APIKeyAuth."""
    key_file = os.path.join(os.path.expanduser("~"), ".pouw_admin_key")
    try:
        with open(key_file, "r", encoding="utf-8") as f:
            return (f.read() or "").strip()
    except Exception:
        return ""


def build_api_key_candidates() -> List[str]:
    """Build de-duplicated key candidates for local integration auth."""
    candidates = [
        os.getenv("POUW_E2E_API_KEY", "").strip(),
        os.getenv("POUW_ADMIN_KEY", "").strip(),
        read_local_admin_key(),
        "",  # fallback: allow localhost trust mode when REQUIRE_LOCAL_AUTH=false
    ]
    uniq: List[str] = []
    for key in candidates:
        if key not in uniq:
            uniq.append(key)
    return uniq


def build_key_try_list(active_api_key: Optional[str], candidates: List[str]) -> List[str]:
    """Try active key first, then remaining candidates."""
    keys_to_try: List[str] = []
    if active_api_key is not None:
        keys_to_try.append(active_api_key)
    for key in candidates:
        if key not in keys_to_try:
            keys_to_try.append(key)
    return keys_to_try


def get_default_rpc_url(path_suffix: str = "") -> str:
    """Return default integration RPC URL, optionally appending a path suffix."""
    base = os.getenv("POUW_E2E_RPC_URL", "https://127.0.0.1:8545").strip().rstrip("/")
    suffix = (path_suffix or "").strip()
    if not suffix:
        return base
    if not suffix.startswith("/"):
        suffix = "/" + suffix
    return base + suffix


def create_insecure_ssl_context() -> ssl.SSLContext:
    """Create permissive SSL context for local self-signed integration endpoint."""
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def build_rpc_headers(api_key: str = "", auth_user: str = "") -> dict:
    """Build common JSON-RPC headers with optional API key and auth user."""
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["X-API-Key"] = api_key
    if auth_user:
        headers["X-Auth-User"] = auth_user
    return headers
